### ISSUE TITLE
a couple questions

### ISSUE THREAD

**Issue by Amin456789** [ThisisBillhe/tiny-stable-diffusion#2]
Hello!

thank you for this, this is pretty cool!

i have two questions
1. does it work with cpu too? i used onnx int8 version in the past and it worked very well with cpu, how about tiny sd?

2. can u please work on AnimateDiff support too? it will be very handy if we have a tiny animatediff with cpu support for us laptop cpu users

kinds regards

**Comment by ThisisBillhe** [comment]
Hi! I tested it over ONNX with cpu. It seems that the memory is not the main constraint in this case. Quantization can reduce the RAM consumption for ~1GB. However, the speed can be slower.

**Comment by Amin456789** [comment]
thank you for the answer
